name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  verify:
    uses: gomlang/verification/.github/workflows/ecosystem-ci.yml@b4e989aacb50c8825c0aea86f7cb276d3748b39c
    with:
      module: goir
      verification-ref: b4e989aacb50c8825c0aea86f7cb276d3748b39c
