name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  verify:
    uses: gomlang/verification/.github/workflows/ecosystem-ci.yml@857b1b5e7051d15999f66afd37cc0b0ad944f42e
    with:
      module: goir
      verification-ref: 857b1b5e7051d15999f66afd37cc0b0ad944f42e
