name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  verify:
    uses: gomlang/verification/.github/workflows/ecosystem-ci.yml@23ad70d702978884dcd64321910f3999731b06c1
    with:
      module: goir
      verification-ref: 23ad70d702978884dcd64321910f3999731b06c1
